- !ruby/object:CloudCapacitor::VMType
  name: c3_large
  cpu: 2
  mem: 3.75
  price: 0.105
  category: c3
- !ruby/object:CloudCapacitor::VMType
  name: c3_xlarge
  cpu: 4
  mem: 7.5
  price: 0.21
  category: c3
- !ruby/object:CloudCapacitor::VMType
  name: c3_2xlarge
  cpu: 8
  mem: 15
  price: 0.42
  category: c3
- !ruby/object:CloudCapacitor::VMType
  name: m3_medium
  cpu: 1
  mem: 3.75
  price: 0.07
  category: m3
- !ruby/object:CloudCapacitor::VMType
  name: m3_large
  cpu: 2
  mem: 7.5
  price: 0.14
  category: m3
- !ruby/object:CloudCapacitor::VMType
  name: m3_xlarge
  cpu: 4
  mem: 15
  price: 0.28
  category: m3
- !ruby/object:CloudCapacitor::VMType
  name: m3_2xlarge
  cpu: 8
  mem: 30.0
  price: 0.56
  category: m3
